variables:
  MAVEN_REPO: "$CI_PROJECT_DIR/.m2"

image: maven:3-jdk-8

stages:
  - deploy
  
services:
  - postgres:latest
  
variables:
  RANCHER_URL: http://178.151.252.225:7005
  RANCHER_ACCESS_KEY: A507F5A5EEBE85EC980A
  RANCHER_SECRET_KEY: 4DTicqNTJfTFF9Zf5GcyoWTkegL8PTckz9Z5tk1K  
    
webapp_deploy:
  stage: deploy
  image: cdrx/rancher-gitlab-deploy
  script:
  - upgrade --stack schoolreader --service schoolreader-api --new-image registry.gitlab.com/bitmedia/schoolreader/schoolreader-api/dev/api
  - upgrade --stack schoolreader --service schoolreader-postgres --new-image registry.gitlab.com/bitmedia/schoolreader/schoolreader-api/dev/postgres
