variables:
  MAVEN_REPO: "$CI_PROJECT_DIR/.m2"


stages:
  - deploy

services:
  - postgres:latest


webapp_deploy:
  stage: deploy
  image: cdrx/rancher-gitlab-deploy

  script:
    - upgrade --stack schoolreader --rancher-secret 4DTicqNTJfTFF9Zf5GcyoWTkegL8PTckz9Z5tk1K --rancher-key A507F5A5EEBE85EC980A  --rancher-url http://178.151.252.225:7005  --stack schoolreader --service schoolreader-api --new-image registry.gitlab.com/bitmedia/schoolreader/schoolreader-api/dev/api
    - upgrade --stack schoolreader  --rancher-secret 4DTicqNTJfTFF9Zf5GcyoWTkegL8PTckz9Z5tk1K --rancher-key A507F5A5EEBE85EC980A --rancher-url http://178.151.252.225:7005  --stack schoolreader --service schoolreader-postgres --new-image  bitmedia/schoolreader/schoolreader-api/dev/postgres
