
INSERT INTO public.SR_TASK ( TITLE,LOCATION,CATEGORY,COUNT_OF_REPEATS ) VALUES ( '54 title','Pure Code','A',3);
INSERT INTO public.SR_TASK ( TITLE,LOCATION,CATEGORY,COUNT_OF_REPEATS ) VALUES ( '55 title','Robinson Cruso','B',4);
