
INSERT INTO public.SR_TASK_PUPIL  ( SRP_ID,SRTA_ID, COUNT_OF_SOLVED_REPEATS,STATUS,TYPE) VALUES           ( 2, 1, 3, 'In_checking','Class');
INSERT INTO public.SR_TASK_PUPIL  ( SRP_ID,SRTA_ID, COUNT_OF_SOLVED_REPEATS,STATUS,TYPE)  VALUES             ( 2, 2, 0, 'In_progress','Class');


INSERT INTO public.SR_TASK_PUPIL  ( SRP_ID,SRTA_ID,  COUNT_OF_SOLVED_REPEATS,STATUS,TYPE) VALUES           ( 1, 1, 0, 'In_progress','Class');
INSERT INTO public.SR_TASK_PUPIL  ( SRP_ID,SRTA_ID, COUNT_OF_SOLVED_REPEATS,STATUS,TYPE)  VALUES             ( 1, 2, 0, 'In_progress','Class');

