
INSERT INTO public.SR_TASK_PUPIL  ( SRP_ID,SRTA_ID, COUNT_OF_REPEATS, COUNT_OF_SOLVED_REPEATS,STATUS,CATEGORY) VALUES           ( 2, 1, 4,4, 'Done','A');
INSERT INTO public.SR_TASK_PUPIL  ( SRP_ID,SRTA_ID, COUNT_OF_REPEATS,COUNT_OF_SOLVED_REPEATS,STATUS,CATEGORY)  VALUES             ( 2, 2, 3,3, 'Done','B');
INSERT INTO public.SR_TASK_PUPIL ( SRP_ID,SRTA_ID,  COUNT_OF_REPEATS,COUNT_OF_SOLVED_REPEATS,STATUS,CATEGORY) VALUES            ( 2, 1, 2,2, 'Done','C');
