
INSERT INTO public.SR_TASK_PUPIL  ( SRP_ID,SRTA_ID, COUNT_OF_SOLVED_REPEATS,STATUS,TYPE) VALUES           ( 2, 1, 4, 'Done','Class');
INSERT INTO public.SR_TASK_PUPIL  ( SRP_ID,SRTA_ID, COUNT_OF_SOLVED_REPEATS,STATUS,TYPE)  VALUES             ( 2, 2, 3, 'Done','Class');
INSERT INTO public.SR_TASK_PUPIL ( SRP_ID,SRTA_ID,  COUNT_OF_SOLVED_REPEATS,STATUS,TYPE) VALUES            ( 2, 1, 2, 'Done','Class');

INSERT INTO public.SR_TASK_PUPIL  ( SRP_ID,SRTA_ID,  COUNT_OF_SOLVED_REPEATS,STATUS,TYPE) VALUES           ( 1, 1, 4, 'Done','Class');
INSERT INTO public.SR_TASK_PUPIL  ( SRP_ID,SRTA_ID, COUNT_OF_SOLVED_REPEATS,STATUS,TYPE)  VALUES             ( 1, 2, 2, 'In_progress','Class');
INSERT INTO public.SR_TASK_PUPIL ( SRP_ID,SRTA_ID, COUNT_OF_SOLVED_REPEATS,STATUS,TYPE) VALUES            ( 1, 1,2, 'In_checking','Class');
